import { SideBar } from "side-bar.slint";
import { AboutPage } from "about-page/about-page.slint";
import { PreferencesPage } from "preferences/preferences-page.slint";
import { TabWidget, ScrollView } from "std-widgets.slint";

//export { TableViewPageAdapter }

export component AppWindow inherits Window {
    preferred-width: 850px;
    preferred-height: 700px;
    title: "iNFekt NFO Viewer";
    icon: @image-url("../assets/infekt-icons/iNFekt_6_256x256x32.png");

    callback sidebar-clicked-open-file();

    in-out property <int> loaded-nfo-id; // XXX: used as a trigger to re-render NFO images.
    pure callback render-loaded-nfo-image(int, string) -> image;

    in property <length> loaded-nfo-width-pixels;
    in property <length> loaded-nfo-height-pixels;

    HorizontalLayout {
        side-bar := SideBar {
            model: [
                {
                    label-text: @tr("Open File..."),
                    icon: @image-url("../assets/tabler-icons/outline/folder-open.svg")
                },
                {
                    label-text: @tr("Preferences"),
                    icon: @image-url("../assets/tabler-icons/outline/settings.svg")
                },
                {
                    label-text: @tr("About"),
                    icon: @image-url("../assets/tabler-icons/outline/info-hexagon.svg")
                },
            ];

            changed current-item => {
                if (side-bar.current-item == 0) {
                    // TODO: actually do this on click, not only on change.
                    root.sidebar-clicked-open-file();
                    loaded-nfo-id += 1; // XXX: temp solution
                }
            }
        }

        if(side-bar.current-item == 0): TabWidget {
            // TODO: this is a WIP solution, later this will be structured into components etc.
            // when we implement text selection and so on.

            Tab {
                title: @tr("Rendered");

                ScrollView {
                    viewport-width: loaded-nfo-width-pixels;
                    viewport-height: loaded-nfo-height-pixels;

                    Image {
                        source: render-loaded-nfo-image(loaded-nfo-id, "rendered");
                    }
                }
            }

            Tab {
                title: @tr("Classic");

                ScrollView {
                    viewport-width: loaded-nfo-width-pixels;
                    viewport-height: loaded-nfo-height-pixels;
                    Rectangle {
                        width: loaded-nfo-width-pixels;
                        height: loaded-nfo-height-pixels;
                        background: lightblue;

                        Rectangle {
                            width: 100px;
                            height: 100px;
                            background: red;
                        }
                    }
                }
            }

            Tab {
                title: @tr("Text-Only");

                ScrollView {
                    viewport-width: loaded-nfo-width-pixels;
                    viewport-height: loaded-nfo-height-pixels;

                    Rectangle {
                        width: loaded-nfo-width-pixels;
                        height: loaded-nfo-height-pixels;
                        background: lightgreen;

                        Rectangle {
                            width: 100px;
                            height: 100px;
                            background: red;
                        }
                    }
                }
            }

            Tab {
                title: @tr("File Info");
                Rectangle {
                    background: lightgreen;
                }
            }
        }

        if(side-bar.current-item == 1): PreferencesPage { }
        if(side-bar.current-item == 2): AboutPage { }
    }
}
