import { SideBar } from "side-bar.slint";
import { AboutPage } from "about-page/about-page.slint";
import { MainView } from "main-view/main-view.slint";
import { PreferencesPage } from "preferences/preferences-page.slint";

//export { TableViewPageAdapter }

export component AppWindow inherits Window {
    width: 850px;
    height: 700px;
    title: "iNFekt NFO Viewer";
    icon: @image-url("../assets/infekt-icons/iNFekt_6_256x256x32.png");

    callback sidebar-clicked-open-file();

    in-out property <string> loaded-nfo-classic;
    in-out property <string> loaded-nfo-text-only;

    HorizontalLayout {
        side-bar := SideBar {
            model: [
                {
                    label-text: @tr("Open File..."),
                    icon: @image-url("../assets/tabler-icons/outline/folder-open.svg")
                },
                {
                    label-text: @tr("Preferences"),
                    icon: @image-url("../assets/tabler-icons/outline/settings.svg")
                },
                {
                    label-text: @tr("About"),
                    icon: @image-url("../assets/tabler-icons/outline/info-hexagon.svg")
                },
            ];

            changed current-item => {
                if (side-bar.current-item == 0) {
                    // TODO: actually do this on click, not only on change.
                    root.sidebar-clicked-open-file();
                }
            }
        }

        if(side-bar.current-item == 0): MainView {
            loaded-nfo-classic: loaded-nfo-classic;
            loaded-nfo-text-only: loaded-nfo-text-only;
        }
        if(side-bar.current-item == 1): PreferencesPage { }
        if(side-bar.current-item == 2): AboutPage { }
    }
}
