import { VerticalBox, HorizontalBox, TabWidget, Button, ScrollView } from "std-widgets.slint";

export component MainView inherits VerticalBox {
    padding: 0;

    in-out property <string> loaded-nfo-classic;
    in-out property <string> loaded-nfo-text-only;

/*
    Button {
        text: @tr("Open File...");
        icon: @image-url("../../assets/tabler-icons/outline/folder-open.svg");
        clicked => {
            
        }
    }
*/
    TabWidget {
        Tab {
            title: @tr("Rendered");
            Rectangle {
                background: darkorange;
            }
        }

        Tab {
            title: @tr("Classic");

            ScrollView {
                Text {
                    font-family: "monospace";
                    text: loaded-nfo-classic;
                }
            }
        }

        Tab {
            title: @tr("Text-Only");

            ScrollView {
                Text {
                    font-family: "monospace";
                    text: loaded-nfo-text-only;
                }
            }
        }

        Tab {
            title: @tr("File Info");
            Rectangle {
                background: lightgreen;
            }
        }
    }

    @children
}
